name: sms_plugin
description: A local plugin for sending SMS with SIM support.
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.sms_plugin
        pluginClass: SmsPlugin
